# Generated by Django 5.2.1 on 2025-10-01 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('enlace', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('foto', models.URLField(blank=True, max_length=500, null=True)),
                ('enlace', models.URLField(unique=True)),
                ('num_capitulos', models.IntegerField(default=0)),
                ('extension', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='libros.extension')),
            ],
        ),
        migrations.CreateModel(
            name='Libreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='librerias', to=settings.AUTH_USER_MODEL)),
                ('libros', models.ManyToManyField(blank=True, related_name='librerias', to='libros.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Capitulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.URLField(unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('visto', models.BooleanField(default=False)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='libros.libro')),
            ],
        ),
    ]
