# Generated by Django 5.2.1 on 2025-06-02 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('enlace', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('enlace', models.URLField(unique=True)),
                ('libreria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='libros.libreria')),
            ],
        ),
        migrations.CreateModel(
            name='Capitulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.URLField(unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('visto', models.BooleanField(default=False)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='libros.libro')),
            ],
        ),
    ]
