# Generated by Django 5.2.1 on 2025-06-03 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='extension',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='extensiones', to='libros.extension'),
        ),
    ]
