# Generated by Django 5.2.1 on 2025-09-26 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='libreria',
        ),
        migrations.AddField(
            model_name='libreria',
            name='libros',
            field=models.ManyToManyField(blank=True, related_name='librerias', to='libros.libro'),
        ),
        migrations.AddField(
            model_name='libreria',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='librerias', to=settings.AUTH_USER_MODEL),
        ),
    ]
