# Generated by Django 5.2.1 on 2025-12-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulos',
            name='enlace',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name='capitulos',
            unique_together={('libro', 'enlace')},
        ),
        migrations.AddIndex(
            model_name='capitulos',
            index=models.Index(fields=['enlace'], name='libros_capi_enlace_08409e_idx'),
        ),
    ]
