# Generated by Django 5.2.1 on 2025-09-29 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_remove_libro_libreria_libreria_libros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libreria',
            name='libros',
        ),
        migrations.AddField(
            model_name='libreria',
            name='libros',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='librerias', to='libros.libro'),
        ),
    ]
