# Generated by Django 5.2.1 on 2025-06-03 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_libro_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='extension',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='libros.extension'),
        ),
    ]
