# Generated by Django 5.2.1 on 2026-05-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_remove_capitulos_visto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulos',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
