# Generated by Django 5.2.1 on 2025-09-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_remove_libreria_libros_libreria_libros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libreria',
            name='libros',
        ),
        migrations.AddField(
            model_name='libreria',
            name='libros',
            field=models.ManyToManyField(blank=True, related_name='librerias', to='libros.libro'),
        ),
    ]
