# Generated by Django 5.2.1 on 2025-06-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_alter_libro_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='num_capitulos',
            field=models.IntegerField(default=0),
        ),
    ]
