# Generated by Django 5.2.1 on 2025-06-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_libro_num_capitulos'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='foto',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
