# Generated by Django 5.2.1 on 2025-06-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_libro_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulos',
            name='enlace',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='enlace',
            field=models.URLField(),
        ),
    ]
