# Generated by Django 5.2.1 on 2025-06-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_alter_capitulos_enlace_alter_libro_enlace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulos',
            name='enlace',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='enlace',
            field=models.URLField(unique=True),
        ),
    ]
